#!/bin/zsh

# Mattermost Load Test Shell

# Copyright (c) 2024 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

function _sshAgent {
    echo "Adding SSH key to the agent..."
    if [ -z "$(pgrep ssh-agent)" ]; then
        echo "Starting ssh-agent..."
        eval $(ssh-agent -s)
    else
        echo "ssh-agent is already running..."
    fi
    echo "Adding the key..."
    ssh-add /root/.ssh/id_rsa
}

function _checkConfig {
    echo "Checking the configuration..."
    if [ ! -f /mmlt/config/deployer.sample.json ]; then
        echo "Deployer configuration file not found. Copying..."
        cp /mmlt/config.default/deployer.sample.json /mmlt/config/deployer.json
        NEW_VERSION=$(curl -s https://api.github.com/repos/mattermost/mattermost-load-test-ng/releases/latest | jq -r .tag_name | sed 's/^v//') sed -i '' "s|/v[0-9]*\.[0-9]*\.[0-9]*/|/v${NEW_VERSION}/|g" /mmlt/config/deployer.json
    fi
    if [ ! -f /mmlt/config/config.sample.json ]; then
        echo "Config configuration file not found. Cppying..."
        cp /mmlt/config.default/config.sample.json /mmlt/config/config.json
    fi
}

echo "Setting up MMLT Shell..."
_sshAgent
_checkConfig
echo "MMLT Shell READY..."

# Pass control to the CMD
exec "$@"
